/**
 * Catálogo de teste (seção 13.2). Cada linha é um produto; `products.ts` completa descrição,
 * ficha, estoque, imagens e variantes a partir daqui e dos padrões de cada categoria.
 *
 * Chaves curtas, para o arquivo caber na tela:
 * n nome, c caminho da categoria, p preço em reais, g peso em gramas, t texto de abertura da descrição,
 * sci nome científico, pop nome popular, luz, rega, amb ambiente, pet, cuid nível de cuidado, h altura (cm),
 * mat material, cor, boca/base diâmetros (cm), l largura, pr profundidade, cap litros, furo drenagem,
 * uso interno/externo, vaso (artificial acompanha vaso), sub subtipo para filtros, marca,
 * v variantes [nome, opções, preço, peso?].
 */

export type Luz = "FULL_SUN" | "PARTIAL_SHADE" | "SHADE" | "INDIRECT_LIGHT";
export type Amb = "INDOOR" | "OUTDOOR" | "BOTH";

export type RawProduct = {
  n: string;
  c: string;
  p: number;
  g: number;
  t: string;
  sci?: string;
  pop?: string;
  luz?: Luz;
  rega?: string;
  amb?: Amb;
  pet?: "SAFE" | "NOT_SAFE" | "TOXIC";
  cuid?: "EASY" | "MODERATE" | "DEMANDING";
  h?: number;
  mat?: string;
  cor?: string;
  boca?: number;
  base?: number;
  l?: number;
  pr?: number;
  cap?: number;
  furo?: boolean;
  uso?: Amb;
  vaso?: boolean;
  sub?: string;
  marca?: string;
  v?: Array<[name: string, options: Record<string, string>, price: number, grams?: number]>;
};

const R5 = "A cada 5 a 7 dias, quando o substrato estiver seco";
const R7 = "Uma vez por semana, sem encharcar";
const R3 = "A cada 2 ou 3 dias, mantendo a terra levemente úmida";
const R15 = "A cada 10 a 15 dias, com pouca água";
const R1 = "Todos os dias no calor, direto na terra";

export const rawProducts: RawProduct[] = [
  // ── Plantas naturais ──
  {
    n: "Kit três folhagens para iniciantes",
    c: "plantas-naturais",
    p: 189,
    g: 3200,
    t: "Três plantas resistentes para quem está começando: uma zamioculca, uma jiboia e uma espada-de-são-jorge, todas em vasos de cultivo de 15 cm. Ficam bem juntas em uma estante ou separadas pela casa.",
    pop: "Folhagens variadas",
    luz: "INDIRECT_LIGHT",
    rega: R7,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 35,
  },
  {
    n: "Samambaia americana em cuia",
    c: "plantas-naturais",
    p: 79,
    g: 1800,
    t: "Samambaia cheia, com folhas pendentes que passam da borda da cuia. Gosta de umidade e de claridade sem sol direto, por isso vai bem em varandas cobertas e banheiros iluminados.",
    sci: "Nephrolepis exaltata",
    pop: "Samambaia americana",
    luz: "PARTIAL_SHADE",
    rega: R3,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "MODERATE",
    h: 45,
  },

  // Orquídeas
  {
    n: "Orquídea Phalaenopsis branca 2 hastes",
    c: "plantas-naturais/orquideas",
    p: 249,
    g: 1500,
    t: "A orquídea mais pedida da loja: duas hastes carregadas de flores brancas grandes, com botões ainda por abrir. A floração dura de seis a oito semanas dentro de casa.",
    sci: "Phalaenopsis amabilis",
    pop: "Orquídea borboleta",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 60,
  },
  {
    n: "Orquídea Phalaenopsis rosa em cachepot de cerâmica",
    c: "plantas-naturais/orquideas",
    p: 289,
    g: 2300,
    t: "Phalaenopsis de flores cor-de-rosa com o centro mais escuro, já acomodada em um cachepot de cerâmica branca. Chega pronta para presentear, sem precisar de mais nada.",
    sci: "Phalaenopsis hybrid",
    pop: "Orquídea borboleta",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 55,
  },
  {
    n: "Orquídea Cymbidium",
    c: "plantas-naturais/orquideas",
    p: 390,
    g: 4200,
    t: "Hastes longas e eretas, com dez a quinze flores cada, e folhas finas que formam uma touceira elegante. Prefere lugares frescos e muito claros, como varandas cobertas.",
    sci: "Cymbidium hybrid",
    pop: "Cimbídio",
    luz: "PARTIAL_SHADE",
    rega: R7,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "MODERATE",
    h: 80,
  },
  {
    n: "Orquídea Dendrobium",
    c: "plantas-naturais/orquideas",
    p: 159,
    g: 1300,
    t: "Flores pequenas e numerosas ao longo do caule, em tons de lilás e branco. É uma orquídea que aprecia bastante claridade e floresce com fartura quando recebe sol suave pela manhã.",
    sci: "Dendrobium nobile",
    pop: "Olho-de-boneca",
    luz: "PARTIAL_SHADE",
    rega: R5,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "MODERATE",
    h: 50,
  },
  {
    n: "Mini orquídea Phalaenopsis",
    c: "plantas-naturais/orquideas",
    p: 89,
    g: 600,
    t: "Versão compacta da orquídea borboleta, com flores delicadas em uma haste. Cabe em mesa de trabalho, cabeceira e prateleira, e é um presente que agrada sem ocupar espaço.",
    sci: "Phalaenopsis hybrid",
    pop: "Mini orquídea",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 25,
    v: [
      ["Branca", { Cor: "Branca" }, 89],
      ["Rosa", { Cor: "Rosa" }, 89],
      ["Lilás", { Cor: "Lilás" }, 95],
    ],
  },

  // Plantas ornamentais
  {
    n: "Zamioculca",
    c: "plantas-naturais/plantas-ornamentais",
    p: 89,
    g: 2000,
    t: "Folhas grossas e brilhantes, que guardam água e aguentam semanas de esquecimento. É a planta indicada para ambientes com pouca luz e para quem viaja com frequência.",
    sci: "Zamioculcas zamiifolia",
    pop: "Zamioculca",
    luz: "SHADE",
    rega: R15,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 40,
    v: [
      ["Pequena, 40 cm", { Tamanho: "P" }, 89, 2000],
      ["Média, 60 cm", { Tamanho: "M" }, 149, 4000],
      ["Grande, 90 cm", { Tamanho: "G" }, 320, 9000],
    ],
  },
  {
    n: "Costela-de-adão",
    c: "plantas-naturais/plantas-ornamentais",
    p: 189,
    g: 5000,
    t: "Folhas grandes e recortadas, que viraram símbolo da decoração com plantas. Cresce rápido em ambiente claro e pode ser conduzida em tutor para ganhar altura.",
    sci: "Monstera deliciosa",
    pop: "Costela-de-adão",
    luz: "INDIRECT_LIGHT",
    rega: R7,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 70,
  },
  {
    n: "Espada-de-são-jorge",
    c: "plantas-naturais/plantas-ornamentais",
    p: 79,
    g: 2500,
    t: "Folhas eretas e firmes, com bordas verde-escuras. Tolera pouca luz, ar-condicionado e regas espaçadas, e por isso é uma das plantas mais resistentes para interiores.",
    sci: "Dracaena trifasciata",
    pop: "Espada-de-são-jorge",
    luz: "SHADE",
    rega: R15,
    amb: "BOTH",
    pet: "TOXIC",
    cuid: "EASY",
    h: 60,
  },
  {
    n: "Jiboia em cachepot",
    c: "plantas-naturais/plantas-ornamentais",
    p: 119,
    g: 2200,
    t: "Ramos pendentes com folhas em forma de coração, manchadas de verde-claro. Vem em cachepot de cerâmica e pode ficar em prateleiras altas, de onde os ramos descem.",
    sci: "Epipremnum aureum",
    pop: "Jiboia",
    luz: "INDIRECT_LIGHT",
    rega: R7,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 35,
  },
  {
    n: "Lírio-da-paz",
    c: "plantas-naturais/plantas-ornamentais",
    p: 99,
    g: 2400,
    t: "Folhagem verde-escura com flores brancas em formato de concha, que aparecem várias vezes ao ano. Avisa quando precisa de água: as folhas murcham e se recuperam logo após a rega.",
    sci: "Spathiphyllum wallisii",
    pop: "Lírio-da-paz",
    luz: "PARTIAL_SHADE",
    rega: R3,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 50,
  },
  {
    n: "Pacová",
    c: "plantas-naturais/plantas-ornamentais",
    p: 139,
    g: 3800,
    t: "Folhas largas, lisas e muito brilhantes, que saem direto da base. Nativa da Mata Atlântica, gosta de sombra clara e de umidade, e dá volume a cantos vazios da sala.",
    sci: "Philodendron martianum",
    pop: "Pacová",
    luz: "PARTIAL_SHADE",
    rega: R7,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 55,
  },

  // Flores em vasos
  {
    n: "Kalanchoe",
    c: "plantas-naturais/flores-em-vasos",
    p: 29,
    g: 500,
    t: "Suculenta de floração farta, com cachos de flores pequenas que duram semanas. Precisa de bastante luz e pouca água, e costuma voltar a florir no ano seguinte.",
    sci: "Kalanchoe blossfeldiana",
    pop: "Flor-da-fortuna",
    luz: "FULL_SUN",
    rega: R7,
    amb: "BOTH",
    pet: "TOXIC",
    cuid: "EASY",
    h: 20,
    v: [
      ["Vermelha", { Cor: "Vermelha" }, 29],
      ["Amarela", { Cor: "Amarela" }, 29],
      ["Rosa", { Cor: "Rosa" }, 29],
      ["Laranja", { Cor: "Laranja" }, 29],
    ],
  },
  {
    n: "Antúrio vermelho",
    c: "plantas-naturais/flores-em-vasos",
    p: 129,
    g: 2000,
    t: "Flores vermelhas e enceradas em formato de coração, que ficam abertas por meses. É uma planta de interior clássica, que mantém a floração o ano todo em ambiente claro.",
    sci: "Anthurium andraeanum",
    pop: "Antúrio",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "EASY",
    h: 45,
  },
  {
    n: "Violeta",
    c: "plantas-naturais/flores-em-vasos",
    p: 29,
    g: 350,
    t: "Folhas aveludadas e flores de cor intensa no centro da planta. Gosta de janela iluminada e de água colocada no pratinho, sem molhar as folhas.",
    sci: "Saintpaulia ionantha",
    pop: "Violeta-africana",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "MODERATE",
    h: 12,
  },
  {
    n: "Begônia",
    c: "plantas-naturais/flores-em-vasos",
    p: 49,
    g: 600,
    t: "Flores dobradas, parecidas com pequenas rosas, sobre folhas verde-escuras. Floresce por longos períodos em varandas cobertas e peitoris bem iluminados.",
    sci: "Begonia elatior",
    pop: "Begônia",
    luz: "PARTIAL_SHADE",
    rega: R5,
    amb: "BOTH",
    pet: "TOXIC",
    cuid: "MODERATE",
    h: 25,
  },
  {
    n: "Mini rosa",
    c: "plantas-naturais/flores-em-vasos",
    p: 39,
    g: 500,
    t: "Roseira em miniatura, com vários botões por vaso. Precisa de sol direto por algumas horas e de rega frequente; depois da floração pode ser plantada no jardim.",
    sci: "Rosa chinensis",
    pop: "Mini rosa",
    luz: "FULL_SUN",
    rega: R3,
    amb: "OUTDOOR",
    pet: "SAFE",
    cuid: "MODERATE",
    h: 25,
  },

  // Cactos e suculentas
  {
    n: "Kit 3 suculentas em vasos de cerâmica",
    c: "plantas-naturais/cactos-e-suculentas",
    p: 89,
    g: 900,
    t: "Três suculentas de espécies diferentes, cada uma em um vasinho de cerâmica branca com furo. Formam um conjunto para o peitoril da janela ou a mesa de trabalho.",
    pop: "Suculentas variadas",
    luz: "FULL_SUN",
    rega: R15,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "EASY",
    h: 10,
  },
  {
    n: "Cacto mandacaru",
    c: "plantas-naturais/cactos-e-suculentas",
    p: 149,
    g: 3500,
    t: "Cacto colunar de crescimento vertical, com gomos marcados e espinhos curtos. Tem presença de escultura e pede apenas sol e regas bem espaçadas.",
    sci: "Cereus jamacaru",
    pop: "Mandacaru",
    luz: "FULL_SUN",
    rega: R15,
    amb: "BOTH",
    pet: "NOT_SAFE",
    cuid: "EASY",
    h: 60,
  },
  {
    n: "Echeveria",
    c: "plantas-naturais/cactos-e-suculentas",
    p: 25,
    g: 250,
    t: "Roseta de folhas carnudas em tom verde-acinzentado, com as pontas levemente rosadas quando recebe sol. Uma das suculentas mais fáceis de manter.",
    sci: "Echeveria elegans",
    pop: "Rosa-de-pedra",
    luz: "FULL_SUN",
    rega: R15,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "EASY",
    h: 8,
  },
  {
    n: "Composição de suculentas em bandeja",
    c: "plantas-naturais/cactos-e-suculentas",
    p: 189,
    g: 2800,
    t: "Jardim de suculentas montado em bandeja de cerâmica baixa, com oito a dez mudas de formas e cores diferentes e acabamento de pedrisco.",
    pop: "Suculentas variadas",
    luz: "FULL_SUN",
    rega: R15,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "EASY",
    h: 15,
  },

  // Ervas e temperos
  {
    n: "Manjericão",
    c: "plantas-naturais/ervas-e-temperos",
    p: 19,
    g: 500,
    t: "Folhas largas e perfumadas, prontas para o molho e a salada. Colha sempre pelas pontas, acima de um par de folhas, para a planta ramificar e render mais.",
    sci: "Ocimum basilicum",
    pop: "Manjericão",
    luz: "FULL_SUN",
    rega: R1,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "EASY",
    h: 25,
  },
  {
    n: "Alecrim",
    c: "plantas-naturais/ervas-e-temperos",
    p: 22,
    g: 600,
    t: "Arbusto aromático de folhas finas, que perfuma assados e a própria varanda. Prefere sol pleno e terra mais seca, e vive por anos no mesmo vaso.",
    sci: "Salvia rosmarinus",
    pop: "Alecrim",
    luz: "FULL_SUN",
    rega: R5,
    amb: "OUTDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 30,
  },
  {
    n: "Hortelã",
    c: "plantas-naturais/ervas-e-temperos",
    p: 19,
    g: 500,
    t: "Erva de crescimento rápido, para chás, sucos e sobremesas. Espalha-se com facilidade, por isso rende melhor em vaso próprio, com terra sempre úmida.",
    sci: "Mentha spicata",
    pop: "Hortelã",
    luz: "PARTIAL_SHADE",
    rega: R1,
    amb: "BOTH",
    pet: "NOT_SAFE",
    cuid: "EASY",
    h: 20,
  },
  {
    n: "Kit horta de temperos",
    c: "plantas-naturais/ervas-e-temperos",
    p: 99,
    g: 2600,
    t: "Manjericão, alecrim, hortelã, salsinha e cebolinha em cinco vasos de cultivo, para montar a horta na janela da cozinha de uma vez só.",
    pop: "Temperos variados",
    luz: "FULL_SUN",
    rega: R3,
    amb: "BOTH",
    pet: "NOT_SAFE",
    cuid: "EASY",
    h: 25,
  },

  // Caixarias
  {
    n: "Caixa de madeira com mix de suculentas",
    c: "plantas-naturais/caixarias",
    p: 149,
    g: 2400,
    t: "Caixa de pinus tratado com seis suculentas plantadas e acabamento de casca. Tem forro interno e drenagem, e já chega montada.",
    pop: "Suculentas variadas",
    luz: "FULL_SUN",
    rega: R15,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "EASY",
    h: 18,
  },
  {
    n: "Caixote com ervas",
    c: "plantas-naturais/caixarias",
    p: 129,
    g: 3200,
    t: "Caixote rústico com quatro ervas plantadas: manjericão, alecrim, tomilho e orégano. Uma horta pronta para a bancada ou a varanda.",
    pop: "Ervas variadas",
    luz: "FULL_SUN",
    rega: R3,
    amb: "BOTH",
    pet: "SAFE",
    cuid: "EASY",
    h: 30,
  },
  {
    n: "Caixa de madeira com mini orquídeas",
    c: "plantas-naturais/caixarias",
    p: 249,
    g: 2600,
    t: "Três mini orquídeas Phalaenopsis acomodadas em caixa de madeira clara, com musgo cobrindo os vasos. Um presente com cara de arranjo.",
    sci: "Phalaenopsis hybrid",
    pop: "Mini orquídeas",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 28,
  },
  {
    n: "Caixa de madeira com cactos",
    c: "plantas-naturais/caixarias",
    p: 79,
    g: 1500,
    t: "Quatro cactos pequenos de formatos diferentes em caixa de madeira com pedrisco branco. Decoração de pouco cuidado para mesas e estantes ensolaradas.",
    pop: "Cactos variados",
    luz: "FULL_SUN",
    rega: R15,
    amb: "BOTH",
    pet: "NOT_SAFE",
    cuid: "EASY",
    h: 15,
  },

  // ── Arranjos naturais ──
  {
    n: "Arranjo de orquídeas em centro de mesa",
    c: "arranjos",
    p: 480,
    g: 5500,
    t: "Três orquídeas Phalaenopsis brancas plantadas em centro de mesa de cerâmica, com musgo e folhagens na base. Montado no dia da entrega.",
    sci: "Phalaenopsis amabilis",
    pop: "Orquídeas brancas",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 60,
    l: 40,
  },
  {
    n: "Arranjo tropical",
    c: "arranjos",
    p: 320,
    g: 4500,
    t: "Antúrios, helicônias e folhagens tropicais em vaso de vidro. Cores fortes e formas marcantes para recepções, mesas de jantar e comemorações.",
    pop: "Flores tropicais",
    luz: "INDIRECT_LIGHT",
    rega: "Troque a água do vaso a cada 2 dias",
    amb: "INDOOR",
    pet: "TOXIC",
    cuid: "MODERATE",
    h: 70,
    l: 45,
  },
  {
    n: "Arranjo com rosas e folhagens",
    c: "arranjos",
    p: 260,
    g: 3000,
    t: "Rosas colombianas de botão grande combinadas com eucalipto e ruscus, em vaso de vidro. Clássico para aniversários e para agradecer.",
    sci: "Rosa hybrid",
    pop: "Rosas",
    luz: "INDIRECT_LIGHT",
    rega: "Troque a água do vaso a cada 2 dias",
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "MODERATE",
    h: 45,
    l: 35,
  },
  {
    n: "Arranjo alto de orquídeas em vaso de vidro",
    c: "arranjos",
    p: 1100,
    g: 9000,
    t: "Cinco hastes de Phalaenopsis branca em vaso de vidro alto, com galhos secos e musgo. Peça de impacto para recepções, eventos e presentes corporativos.",
    sci: "Phalaenopsis amabilis",
    pop: "Orquídeas brancas",
    luz: "INDIRECT_LIGHT",
    rega: R5,
    amb: "INDOOR",
    pet: "SAFE",
    cuid: "EASY",
    h: 110,
    l: 50,
  },

  // Arranjos artificiais
  {
    n: "Arranjo em centro de mesa com suculentas artificiais",
    c: "arranjos/arranjos-artificiais",
    p: 150,
    g: 1800,
    t: "Suculentas artificiais de vários formatos montadas em bandeja de cerâmica com pedrisco. O acabamento fosco das folhas reproduz o aspecto das plantas de verdade.",
    mat: "Polietileno e cerâmica",
    h: 14,
    l: 32,
    vaso: true,
    sub: "arranjo",
    cor: "Verde",
  },
  {
    n: "Vaso de cerâmica com orquídea Cymbidium artificial",
    c: "arranjos/arranjos-artificiais",
    p: 690,
    g: 5200,
    t: "Hastes de Cymbidium artificial em tom creme, fixadas em vaso de cerâmica esmaltada com musgo. Tem altura e volume para aparadores e recepções.",
    mat: "Silicone e cerâmica",
    h: 85,
    l: 40,
    vaso: true,
    sub: "arranjo",
    cor: "Branco",
  },
  {
    n: "Xícara com rosas artificiais",
    c: "arranjos/arranjos-artificiais",
    p: 189,
    g: 900,
    t: "Rosas artificiais em tons de rosa antigo arrumadas em uma xícara de porcelana com pires. Um arranjo pequeno para penteadeira, lavabo e mesa de chá.",
    mat: "Tecido e porcelana",
    h: 18,
    l: 16,
    vaso: true,
    sub: "arranjo",
    cor: "Rosa",
  },
  {
    n: "Centro de mesa com orquídea dourada",
    c: "arranjos/arranjos-artificiais",
    p: 1150,
    g: 7000,
    t: "Arranjo de grande porte com orquídeas artificiais brancas e hastes douradas, em centro de mesa de metal. Pensado para mesas de jantar longas e halls de entrada.",
    mat: "Silicone e metal",
    h: 75,
    l: 70,
    vaso: true,
    sub: "arranjo",
    cor: "Dourado",
  },

  // ── Vasos ──
  {
    n: "Kit 3 vasos de cerâmica natural",
    c: "vasos",
    p: 159,
    g: 3600,
    t: "Três vasos de cerâmica sem esmalte, em tamanhos que se encaixam: 12, 15 e 18 cm de boca. A cor de barro claro combina com qualquer folhagem.",
    mat: "Cerâmica",
    cor: "Terracota",
    h: 16,
    boca: 18,
    base: 11,
    cap: 2.5,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Vaso de cimento cilíndrico",
    c: "vasos",
    p: 119,
    g: 4200,
    t: "Vaso de cimento alisado, de linhas retas e cor cinza natural. O peso dá estabilidade a plantas altas, como espadas e cactos colunares.",
    mat: "Cimento",
    cor: "Cinza",
    h: 24,
    boca: 22,
    base: 22,
    cap: 7,
    furo: true,
    uso: "BOTH",
  },

  // Cerâmica e barro
  {
    n: "Vaso de barro tradicional",
    c: "vasos/ceramica-e-barro",
    p: 29,
    g: 900,
    t: "O vaso de barro de sempre, torneado e queimado em forno. As paredes porosas deixam a terra respirar e evitam o excesso de umidade nas raízes.",
    mat: "Barro",
    cor: "Terracota",
    h: 14,
    boca: 16,
    base: 10,
    cap: 1.5,
    furo: true,
    uso: "BOTH",
    v: [
      ["Pequeno, 16 cm", { Tamanho: "P" }, 29, 900],
      ["Médio, 24 cm", { Tamanho: "M" }, 59, 2400],
      ["Grande, 34 cm", { Tamanho: "G" }, 119, 6000],
    ],
  },
  {
    n: "Vaso de cerâmica vitrificada verde-musgo",
    c: "vasos/ceramica-e-barro",
    p: 189,
    g: 3800,
    t: "Cerâmica de alta temperatura com esmalte verde-musgo brilhante, de tonalidade levemente irregular, que dá profundidade à cor.",
    mat: "Cerâmica vitrificada",
    cor: "Verde",
    h: 26,
    boca: 28,
    base: 17,
    cap: 9,
    furo: true,
    uso: "BOTH",
    v: [
      ["Médio, 28 cm", { Tamanho: "M" }, 189, 3800],
      ["Grande, 38 cm", { Tamanho: "G" }, 320, 7500],
    ],
  },
  {
    n: "Vaso esmaltado azul",
    c: "vasos/ceramica-e-barro",
    p: 249,
    g: 5200,
    t: "Vaso bojudo com esmalte azul-cobalto escorrido, feito à mão. Cada peça sai do forno com um desenho diferente no esmalte.",
    mat: "Cerâmica esmaltada",
    cor: "Azul",
    h: 32,
    boca: 30,
    base: 18,
    cap: 14,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Vaso de cerâmica rústica bojudo",
    c: "vasos/ceramica-e-barro",
    p: 450,
    g: 11000,
    t: "Peça grande de cerâmica com acabamento rústico e textura de torno aparente. Indicado para palmeiras, costelas-de-adão e outras plantas de porte.",
    mat: "Cerâmica",
    cor: "Bege",
    h: 48,
    boca: 44,
    base: 26,
    cap: 40,
    furo: true,
    uso: "BOTH",
  },

  // Porcelana
  {
    n: "Vaso de porcelana branca canelado",
    c: "vasos/porcelana",
    p: 149,
    g: 1400,
    t: "Porcelana branca com caneluras verticais que criam jogo de luz e sombra. Fica bem com flores de corte e com orquídeas no vaso de cultivo.",
    mat: "Porcelana",
    cor: "Branco",
    h: 18,
    boca: 16,
    base: 11,
    cap: 2,
    furo: false,
    uso: "INDOOR",
    v: [
      ["Pequeno, 16 cm", { Tamanho: "P" }, 149, 1400],
      ["Médio, 22 cm", { Tamanho: "M" }, 229, 2300],
    ],
  },
  {
    n: "Vaso de porcelana com borda dourada",
    c: "vasos/porcelana",
    p: 380,
    g: 2600,
    t: "Porcelana branca de paredes finas, com filete dourado pintado à mão na borda. Uma peça delicada para arranjos de flores e mesas postas.",
    mat: "Porcelana",
    cor: "Branco",
    h: 28,
    boca: 18,
    base: 12,
    cap: 4,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso de porcelana fosca cinza",
    c: "vasos/porcelana",
    p: 219,
    g: 1900,
    t: "Porcelana de acabamento fosco em cinza-claro, com formato de ânfora baixa. Funciona sozinha na estante ou com ramos secos.",
    mat: "Porcelana",
    cor: "Cinza",
    h: 24,
    boca: 12,
    base: 10,
    cap: 3,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso solitário de porcelana",
    c: "vasos/porcelana",
    p: 69,
    g: 400,
    t: "Vaso estreito para uma única flor ou um ramo de eucalipto. O gargalo fino mantém a haste em pé sem precisar de espuma floral.",
    mat: "Porcelana",
    cor: "Branco",
    h: 16,
    boca: 3,
    base: 6,
    cap: 0.3,
    furo: false,
    uso: "INDOOR",
  },

  // Vidro
  {
    n: "Vaso de vidro para pendurar círculo 18 × 8 cm",
    c: "vasos/vidro",
    p: 59,
    g: 450,
    t: "Vaso de vidro soprado em formato de círculo, com abertura lateral e alça para pendurar. Feito para plantas aéreas, mini suculentas e pequenos terrários.",
    mat: "Vidro",
    cor: "Transparente",
    h: 18,
    l: 18,
    pr: 8,
    boca: 8,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso de vidro para pendurar coração 18 × 23 cm",
    c: "vasos/vidro",
    p: 89,
    g: 600,
    t: "Vidro soprado em formato de coração, com abertura frontal. Fica leve na janela com uma tillandsia ou com musgo e pedras.",
    mat: "Vidro",
    cor: "Transparente",
    h: 23,
    l: 18,
    pr: 9,
    boca: 9,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso de vidro cilíndrico",
    c: "vasos/vidro",
    p: 79,
    g: 1200,
    t: "Cilindro de vidro grosso e transparente, de base pesada. Serve para flores de corte, velas flutuantes e para o cultivo de plantas na água.",
    mat: "Vidro",
    cor: "Transparente",
    h: 20,
    boca: 12,
    base: 12,
    cap: 2,
    furo: false,
    uso: "INDOOR",
    v: [
      ["20 cm de altura", { Altura: "20 cm" }, 79, 1200],
      ["30 cm de altura", { Altura: "30 cm" }, 129, 2000],
    ],
  },
  {
    n: "Garrafão de vidro para terrário",
    c: "vasos/vidro",
    p: 220,
    g: 3500,
    t: "Garrafão de vidro reciclado, de boca larga, com leve tom esverdeado. O volume permite montar terrários fechados com várias espécies.",
    mat: "Vidro reciclado",
    cor: "Verde",
    h: 38,
    boca: 14,
    base: 22,
    cap: 10,
    furo: false,
    uso: "INDOOR",
  },

  // Fibra de coco
  {
    n: "Vaso de fibra de coco redondo",
    c: "vasos/fibra-de-coco",
    p: 29,
    g: 400,
    t: "Vaso prensado de fibra de coco, material que retém umidade sem encharcar e deixa as raízes arejadas. Substitui o antigo xaxim.",
    mat: "Fibra de coco",
    cor: "Marrom",
    h: 14,
    boca: 20,
    base: 12,
    cap: 2,
    furo: true,
    uso: "BOTH",
    v: [
      ["20 cm de boca", { Tamanho: "P" }, 29, 400],
      ["30 cm de boca", { Tamanho: "M" }, 49, 800],
    ],
  },
  {
    n: "Placa de fibra de coco para jardim vertical",
    c: "vasos/fibra-de-coco",
    p: 39,
    g: 700,
    t: "Placa rígida de fibra de coco para fixar na parede e amarrar orquídeas, bromélias e samambaias, como nos troncos onde elas crescem na natureza.",
    mat: "Fibra de coco",
    cor: "Marrom",
    h: 40,
    l: 20,
    pr: 3,
    furo: false,
    uso: "BOTH",
  },
  {
    n: "Vaso de parede meia-lua de fibra de coco",
    c: "vasos/fibra-de-coco",
    p: 49,
    g: 500,
    t: "Vaso em meia-lua com fundo reto, para prender em muros e painéis. A fibra mantém a umidade que samambaias e avencas pedem.",
    mat: "Fibra de coco",
    cor: "Marrom",
    h: 18,
    l: 30,
    pr: 15,
    boca: 30,
    cap: 3,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Tutor de fibra de coco 60 cm",
    c: "vasos/fibra-de-coco",
    p: 19,
    g: 300,
    t: "Bastão revestido de fibra de coco para conduzir jiboias, filodendros e costelas-de-adão. As raízes aéreas se prendem à fibra e a planta cresce para cima.",
    mat: "Fibra de coco e PVC",
    cor: "Marrom",
    h: 60,
    l: 4,
    pr: 4,
    furo: false,
    uso: "BOTH",
  },

  // Plástico
  {
    n: "Vaso plástico redondo com prato",
    c: "vasos/plastico",
    p: 9,
    g: 150,
    t: "Vaso leve de polipropileno com prato encaixado, para o cultivo do dia a dia. Tem furos no fundo e resiste ao sol sem ressecar.",
    mat: "Polipropileno",
    cor: "Terracota",
    h: 13,
    boca: 15,
    base: 10,
    cap: 1.2,
    furo: true,
    uso: "BOTH",
    v: [
      ["15 cm de boca", { Tamanho: "P" }, 9, 150],
      ["24 cm de boca", { Tamanho: "M" }, 19, 350],
      ["34 cm de boca", { Tamanho: "G" }, 35, 700],
    ],
  },
  {
    n: "Jardineira plástica",
    c: "vasos/plastico",
    p: 49,
    g: 900,
    t: "Jardineira retangular de 60 cm para flores de peitoril e hortas de temperos. Acompanha prato coletor do mesmo comprimento.",
    mat: "Polipropileno",
    cor: "Preto",
    h: 17,
    l: 60,
    pr: 18,
    cap: 12,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Vaso plástico quadrado",
    c: "vasos/plastico",
    p: 29,
    g: 400,
    t: "Vaso quadrado de linhas retas, com pés que afastam o fundo do chão e melhoram a drenagem. Aproveita bem o espaço quando alinhado a outros.",
    mat: "Polipropileno",
    cor: "Cinza",
    h: 24,
    l: 24,
    pr: 24,
    boca: 24,
    cap: 9,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Vaso plástico de parede",
    c: "vasos/plastico",
    p: 15,
    g: 180,
    t: "Vaso meia-cana com furos para parafuso, usado em jardins verticais. Encaixa em treliças e pode ser montado em fileiras.",
    mat: "Polipropileno",
    cor: "Preto",
    h: 14,
    l: 20,
    pr: 11,
    boca: 20,
    cap: 1.5,
    furo: true,
    uso: "BOTH",
  },

  // Polietileno e reciclados
  {
    n: "Vaso de polietileno grande para área externa",
    c: "vasos/polietileno-e-reciclados",
    p: 690,
    g: 6500,
    t: "Vaso de 70 cm de altura em polietileno rotomoldado, com proteção contra raios UV. Parece cimento, mas pesa uma fração e não trinca.",
    mat: "Polietileno",
    cor: "Cinza",
    h: 70,
    boca: 50,
    base: 32,
    cap: 75,
    furo: true,
    uso: "OUTDOOR",
    v: [
      ["Cinza", { Cor: "Cinza" }, 690],
      ["Preto", { Cor: "Preto" }, 690],
      ["Areia", { Cor: "Areia" }, 690],
    ],
  },
  {
    n: "Vaso de material reciclado",
    c: "vasos/polietileno-e-reciclados",
    p: 149,
    g: 2200,
    t: "Feito com plástico reciclado de embalagens, tem textura levemente granulada e cor grafite. Um vaso resistente para varandas e quintais.",
    mat: "Plástico reciclado",
    cor: "Grafite",
    h: 35,
    boca: 36,
    base: 24,
    cap: 22,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Vaso de polietileno cônico médio",
    c: "vasos/polietileno-e-reciclados",
    p: 289,
    g: 3200,
    t: "Formato cônico invertido, com base estreita e boca larga, em acabamento fosco. Valoriza palmeiras e arbustos podados.",
    mat: "Polietileno",
    cor: "Branco",
    h: 50,
    boca: 42,
    base: 24,
    cap: 38,
    furo: true,
    uso: "BOTH",
  },
  {
    n: "Jardineira de polietileno 100 cm",
    c: "vasos/polietileno-e-reciclados",
    p: 420,
    g: 5800,
    t: "Jardineira longa para delimitar varandas e criar cercas vivas em vasos. As paredes duplas isolam as raízes do calor.",
    mat: "Polietileno",
    cor: "Grafite",
    h: 40,
    l: 100,
    pr: 35,
    cap: 90,
    furo: true,
    uso: "OUTDOOR",
  },

  // Vasos decorativos
  {
    n: "Vaso decorativo de vidro Murano",
    c: "vasos/vasos-decorativos",
    p: 690,
    g: 3200,
    t: "Vidro soprado à mão na técnica de Murano, com camadas de cor âmbar e transparente. Nenhuma peça é igual à outra.",
    mat: "Vidro soprado",
    cor: "Âmbar",
    h: 32,
    boca: 14,
    base: 12,
    cap: 3,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso decorativo de cerâmica texturizada",
    c: "vasos/vasos-decorativos",
    p: 329,
    g: 2800,
    t: "Cerâmica branca fosca com relevo de ondas modelado à mão. Uma peça para ficar em destaque, com ou sem flores.",
    mat: "Cerâmica",
    cor: "Branco",
    h: 30,
    boca: 12,
    base: 14,
    cap: 3.5,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso decorativo de vidro âmbar",
    c: "vasos/vasos-decorativos",
    p: 179,
    g: 1500,
    t: "Garrafa de vidro âmbar de gargalo estreito, que filtra a luz em tom quente. Combina com ramos de eucalipto e capim dos pampas.",
    mat: "Vidro",
    cor: "Âmbar",
    h: 28,
    boca: 5,
    base: 13,
    cap: 2,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Vaso decorativo de cerâmica bicolor",
    c: "vasos/vasos-decorativos",
    p: 79,
    g: 900,
    t: "Cerâmica com metade em esmalte branco e metade em barro natural. Pequeno, para compor trios em prateleiras e nichos.",
    mat: "Cerâmica",
    cor: "Branco",
    h: 15,
    boca: 8,
    base: 9,
    cap: 0.8,
    furo: false,
    uso: "INDOOR",
  },

  // Acessórios para vasos
  {
    n: "Prato para vaso",
    c: "vasos/acessorios",
    p: 9,
    g: 120,
    t: "Prato de polipropileno para recolher a água da rega e proteger pisos e móveis. Borda alta e fundo com ranhuras, que afastam o vaso da água parada.",
    mat: "Polipropileno",
    cor: "Terracota",
    h: 3,
    boca: 18,
    furo: false,
    uso: "BOTH",
    v: [
      ["18 cm", { Tamanho: "18 cm" }, 9, 120],
      ["26 cm", { Tamanho: "26 cm" }, 15, 200],
      ["36 cm", { Tamanho: "36 cm" }, 25, 350],
    ],
  },
  {
    n: "Suporte de ferro para vaso",
    c: "vasos/acessorios",
    p: 149,
    g: 2600,
    t: "Suporte de ferro com pintura eletrostática preta e três pés. Eleva o vaso do chão, dá destaque à planta e facilita a limpeza.",
    mat: "Ferro",
    cor: "Preto",
    h: 45,
    boca: 28,
    furo: false,
    uso: "BOTH",
  },
  {
    n: "Gancho dourado",
    c: "vasos/acessorios",
    p: 19,
    g: 80,
    t: "Gancho de metal com banho dourado para pendurar vasos, cuias e vasos de vidro no teto ou em mão-francesa. Acompanha bucha e parafuso.",
    mat: "Metal",
    cor: "Dourado",
    h: 6,
    furo: false,
    uso: "BOTH",
    v: [
      ["Pequeno", { Tamanho: "P" }, 19, 80],
      ["Médio", { Tamanho: "M" }, 25, 120],
      ["Grande", { Tamanho: "G" }, 32, 180],
    ],
  },
  {
    n: "Suporte com rodízios para vaso",
    c: "vasos/acessorios",
    p: 89,
    g: 1300,
    t: "Base redonda com cinco rodízios, que aguenta até 80 kg. Permite mover vasos grandes para limpar o piso ou acompanhar o sol.",
    mat: "Polipropileno e aço",
    cor: "Preto",
    h: 8,
    boca: 35,
    furo: false,
    uso: "BOTH",
  },

  // ── Cachepots ──
  {
    n: "Kit 2 cachepots de cimento",
    c: "cachepots",
    p: 139,
    g: 3400,
    t: "Dois cachepots de cimento em tamanhos diferentes, com acabamento liso e cor cinza natural. Boa dupla para suculentas e cactos.",
    mat: "Cimento",
    cor: "Cinza",
    h: 14,
    boca: 15,
    base: 12,
    cap: 1.8,
    furo: false,
    uso: "BOTH",
  },
  {
    n: "Cachepot de concreto com pés de madeira",
    c: "cachepots",
    p: 219,
    g: 4800,
    t: "Cachepot de concreto apoiado em três pés de madeira torneada. A base elevada dá leveza à peça e protege o piso.",
    mat: "Concreto e madeira",
    cor: "Cinza",
    h: 38,
    boca: 26,
    base: 22,
    cap: 9,
    furo: false,
    uso: "INDOOR",
  },

  // Autoirrigáveis
  {
    n: "Cachepot autoirrigável",
    c: "cachepots/autoirrigaveis",
    p: 59,
    g: 500,
    t: "Reservatório na base e cordão que leva a água às raízes aos poucos. Abastecido, mantém a planta hidratada por até duas semanas.",
    mat: "Polipropileno",
    cor: "Branco",
    h: 16,
    boca: 16,
    base: 12,
    cap: 1.5,
    furo: false,
    uso: "INDOOR",
    marca: "Raiz",
    v: [
      ["Pequeno, 16 cm", { Tamanho: "P" }, 59, 500],
      ["Médio, 22 cm", { Tamanho: "M" }, 89, 800],
      ["Grande, 30 cm", { Tamanho: "G" }, 139, 1400],
    ],
  },
  {
    n: "Cachepot autoirrigável quadrado",
    c: "cachepots/autoirrigaveis",
    p: 79,
    g: 650,
    t: "Versão quadrada, com visor de nível que mostra quando é hora de abastecer. O formato permite alinhar vários lado a lado.",
    mat: "Polipropileno",
    cor: "Grafite",
    h: 18,
    l: 18,
    pr: 18,
    boca: 18,
    cap: 2.2,
    furo: false,
    uso: "INDOOR",
    marca: "Raiz",
  },
  {
    n: "Jardineira autoirrigável",
    c: "cachepots/autoirrigaveis",
    p: 129,
    g: 1200,
    t: "Jardineira de 50 cm com reservatório de dois litros, indicada para hortas de temperos. As ervas recebem água constante sem encharcar.",
    mat: "Polipropileno",
    cor: "Branco",
    h: 18,
    l: 50,
    pr: 18,
    cap: 8,
    furo: false,
    uso: "BOTH",
    marca: "Raiz",
  },
  {
    n: "Mini cachepot autoirrigável de mesa",
    c: "cachepots/autoirrigaveis",
    p: 29,
    g: 180,
    t: "Tamanho para violetas, suculentas e mudas na mesa de trabalho. O reservatório transparente deixa o nível da água à vista.",
    mat: "Polipropileno",
    cor: "Verde",
    h: 10,
    boca: 10,
    base: 8,
    cap: 0.4,
    furo: false,
    uso: "INDOOR",
    marca: "Raiz",
  },

  // Cachepots de cerâmica
  {
    n: "Cachepot de cerâmica mosaico",
    c: "cachepots/ceramica",
    p: 189,
    g: 2600,
    t: "Cerâmica revestida à mão com pastilhas em tons de verde e azul. O mosaico reflete a luz e dá vida a folhagens simples.",
    mat: "Cerâmica",
    cor: "Verde",
    h: 20,
    boca: 20,
    base: 15,
    cap: 4,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de cerâmica branca fosca",
    c: "cachepots/ceramica",
    p: 89,
    g: 1300,
    t: "Cerâmica branca de acabamento fosco e formato cilíndrico. O cachepot neutro que combina com qualquer planta e qualquer ambiente.",
    mat: "Cerâmica",
    cor: "Branco",
    h: 15,
    boca: 15,
    base: 13,
    cap: 2,
    furo: false,
    uso: "INDOOR",
    v: [
      ["15 cm de boca", { Tamanho: "P" }, 89, 1300],
      ["20 cm de boca", { Tamanho: "M" }, 139, 2200],
      ["26 cm de boca", { Tamanho: "G" }, 219, 3800],
    ],
  },
  {
    n: "Cachepot de cerâmica canelada terracota",
    c: "cachepots/ceramica",
    p: 129,
    g: 1800,
    t: "Caneluras verticais marcadas e cor de terracota queimada. Lembra os vasos de barro antigos, com acabamento mais fino.",
    mat: "Cerâmica",
    cor: "Terracota",
    h: 18,
    boca: 19,
    base: 14,
    cap: 3,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de cerâmica esmaltada verde",
    c: "cachepots/ceramica",
    p: 420,
    g: 6500,
    t: "Peça grande com esmalte verde-garrafa de brilho profundo. Tem porte para receber plantas de chão, como ficus e palmeiras.",
    mat: "Cerâmica esmaltada",
    cor: "Verde",
    h: 36,
    boca: 36,
    base: 24,
    cap: 22,
    furo: false,
    uso: "INDOOR",
  },

  // Cachepots de porcelana
  {
    n: "Cachepot de porcelana branca",
    c: "cachepots/porcelana",
    p: 119,
    g: 900,
    t: "Porcelana branca lisa, de paredes finas e brilho discreto. O tamanho é o do vaso de cultivo padrão das orquídeas.",
    mat: "Porcelana",
    cor: "Branco",
    h: 14,
    boca: 14,
    base: 11,
    cap: 1.5,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de porcelana com pés dourados",
    c: "cachepots/porcelana",
    p: 249,
    g: 1500,
    t: "Porcelana branca apoiada em três pés com banho dourado. Um toque de brilho para mesas de centro e aparadores.",
    mat: "Porcelana",
    cor: "Branco",
    h: 18,
    boca: 17,
    base: 12,
    cap: 2.2,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de porcelana azul e branca",
    c: "cachepots/porcelana",
    p: 320,
    g: 2100,
    t: "Decoração floral em azul sobre fundo branco, no estilo da porcelana oriental. Fica bem com orquídeas brancas e antúrios.",
    mat: "Porcelana",
    cor: "Azul",
    h: 20,
    boca: 22,
    base: 14,
    cap: 4,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de porcelana relevo folhas",
    c: "cachepots/porcelana",
    p: 169,
    g: 1100,
    t: "Relevo de folhas em toda a superfície, em porcelana branca fosca. A textura aparece melhor com luz lateral.",
    mat: "Porcelana",
    cor: "Branco",
    h: 15,
    boca: 16,
    base: 11,
    cap: 1.8,
    furo: false,
    uso: "INDOOR",
  },

  // Metal e alumínio
  {
    n: "Cachepot de alumínio escovado",
    c: "cachepots/metal-e-aluminio",
    p: 99,
    g: 400,
    t: "Alumínio com acabamento escovado e borda virada, leve e sem risco de ferrugem. Visual limpo para cozinhas e escritórios.",
    mat: "Alumínio",
    cor: "Prata",
    h: 15,
    boca: 16,
    base: 12,
    cap: 2,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de metal dourado",
    c: "cachepots/metal-e-aluminio",
    p: 149,
    g: 600,
    t: "Metal com banho dourado fosco e formato de taça baixa. Realça o verde das folhas e o branco das orquídeas.",
    mat: "Metal",
    cor: "Dourado",
    h: 16,
    boca: 18,
    base: 11,
    cap: 2.2,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de zinco envelhecido",
    c: "cachepots/metal-e-aluminio",
    p: 79,
    g: 700,
    t: "Balde de zinco com pátina envelhecida e alças laterais. Visual de jardim de campo para ervas e flores de vaso.",
    mat: "Zinco",
    cor: "Cinza",
    h: 18,
    boca: 20,
    base: 14,
    cap: 3.5,
    furo: false,
    uso: "BOTH",
  },
  {
    n: "Cachepot de cobre martelado",
    c: "cachepots/metal-e-aluminio",
    p: 289,
    g: 1100,
    t: "Cobre trabalhado a martelo, com as marcas da batida aparentes. Com o tempo ganha um tom mais escuro, próprio do metal.",
    mat: "Cobre",
    cor: "Cobre",
    h: 20,
    boca: 22,
    base: 15,
    cap: 4.5,
    furo: false,
    uso: "INDOOR",
  },

  // Cachepots de vidro
  {
    n: "Cachepot de vidro",
    c: "cachepots/vidro",
    p: 49,
    g: 800,
    t: "Vidro transparente e grosso, que deixa ver as raízes da orquídea e ajuda a acompanhar a umidade do substrato.",
    mat: "Vidro",
    cor: "Transparente",
    h: 14,
    boca: 14,
    base: 10,
    cap: 1.5,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de vidro canelado",
    c: "cachepots/vidro",
    p: 89,
    g: 1100,
    t: "Vidro prensado com caneluras verticais, que distorcem a luz e escondem parte do vaso de cultivo.",
    mat: "Vidro",
    cor: "Transparente",
    h: 16,
    boca: 16,
    base: 11,
    cap: 2,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de vidro fumê",
    c: "cachepots/vidro",
    p: 119,
    g: 1300,
    t: "Vidro em tom fumê, de formato cilíndrico. Dá um ar contemporâneo a folhagens escuras, como zamioculca e pacová.",
    mat: "Vidro",
    cor: "Fumê",
    h: 18,
    boca: 18,
    base: 18,
    cap: 3.5,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot aquário de vidro",
    c: "cachepots/vidro",
    p: 69,
    g: 900,
    t: "Formato de aquário redondo, de boca larga. Muito usado para terrários abertos e composições de suculentas.",
    mat: "Vidro",
    cor: "Transparente",
    h: 16,
    boca: 14,
    base: 10,
    cap: 2.5,
    furo: false,
    uso: "INDOOR",
  },

  // Cachepots de madeira
  {
    n: "Cachepot de madeira de demolição",
    c: "cachepots/madeira",
    p: 189,
    g: 2400,
    t: "Montado com ripas de peroba de demolição, com marcas e variações de cor da madeira antiga. Tem forro plástico interno.",
    mat: "Madeira de demolição",
    cor: "Madeira",
    h: 22,
    l: 24,
    pr: 24,
    boca: 22,
    cap: 6,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de madeira clara com alça de corda",
    c: "cachepots/madeira",
    p: 129,
    g: 1400,
    t: "Pinus de reflorestamento em tom claro, com alças de corda de sisal. Leve e fácil de mudar de lugar.",
    mat: "Pinus",
    cor: "Madeira",
    h: 20,
    l: 22,
    pr: 22,
    boca: 20,
    cap: 5,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de bambu",
    c: "cachepots/madeira",
    p: 59,
    g: 500,
    t: "Feito de um segmento de bambu envernizado, com o nó natural como fundo. Indicado para mini orquídeas e suculentas.",
    mat: "Bambu",
    cor: "Madeira",
    h: 12,
    boca: 11,
    base: 11,
    cap: 0.7,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de teca torneada",
    c: "cachepots/madeira",
    p: 349,
    g: 2200,
    t: "Teca maciça torneada em uma só peça, com acabamento em óleo que mantém os veios da madeira à mostra.",
    mat: "Teca",
    cor: "Madeira",
    h: 20,
    boca: 22,
    base: 16,
    cap: 3.5,
    furo: false,
    uso: "INDOOR",
  },

  // Cestaria
  {
    n: "Cachepot de cestaria natural",
    c: "cachepots/cestaria",
    p: 89,
    g: 500,
    t: "Cesto trançado à mão em fibra de taboa, de cor palha. Veste vasos de folhagens e aquece a decoração de salas e quartos.",
    mat: "Fibra de taboa",
    cor: "Natural",
    h: 24,
    boca: 26,
    base: 22,
    cap: 9,
    furo: false,
    uso: "INDOOR",
    v: [
      ["Médio, 26 cm", { Tamanho: "M" }, 89, 500],
      ["Grande, 36 cm", { Tamanho: "G" }, 149, 900],
    ],
  },
  {
    n: "Cesto de seagrass com alças",
    c: "cachepots/cestaria",
    p: 139,
    g: 700,
    t: "Trançado de seagrass flexível, com duas alças. Pode ser dobrado na borda para ajustar a altura ao vaso.",
    mat: "Seagrass",
    cor: "Natural",
    h: 30,
    boca: 32,
    base: 28,
    cap: 16,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cachepot de rattan com pés",
    c: "cachepots/cestaria",
    p: 249,
    g: 1600,
    t: "Rattan trançado sobre estrutura de ferro, com pés que elevam o cesto do chão. Um suporte e um cachepot na mesma peça.",
    mat: "Rattan e ferro",
    cor: "Natural",
    h: 50,
    boca: 28,
    base: 24,
    cap: 9,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Cesto de palha bicolor",
    c: "cachepots/cestaria",
    p: 69,
    g: 350,
    t: "Palha trançada com a metade inferior tingida de preto. Tamanho pequeno, para vasos de 15 cm.",
    mat: "Palha",
    cor: "Natural",
    h: 18,
    boca: 18,
    base: 15,
    cap: 3,
    furo: false,
    uso: "INDOOR",
  },

  // Cachepots de plástico
  {
    n: "Cachepot de plástico com acabamento fosco",
    c: "cachepots/plastico",
    p: 29,
    g: 200,
    t: "Polipropileno de acabamento fosco, que lembra cerâmica à primeira vista. Leve, não quebra e é fácil de lavar.",
    mat: "Polipropileno",
    cor: "Branco",
    h: 14,
    boca: 15,
    base: 11,
    cap: 1.6,
    furo: false,
    uso: "BOTH",
    v: [
      ["Branco", { Cor: "Branco" }, 29],
      ["Grafite", { Cor: "Grafite" }, 29],
      ["Areia", { Cor: "Areia" }, 29],
    ],
  },
  {
    n: "Cachepot de plástico texturizado",
    c: "cachepots/plastico",
    p: 39,
    g: 280,
    t: "Superfície com textura de linho, que disfarça marcas de uso. Tem fundo reforçado e bordas arredondadas.",
    mat: "Polipropileno",
    cor: "Cinza",
    h: 17,
    boca: 19,
    base: 13,
    cap: 2.8,
    furo: false,
    uso: "BOTH",
  },
  {
    n: "Cachepot de plástico suspenso",
    c: "cachepots/plastico",
    p: 35,
    g: 260,
    t: "Cachepot com três correntes e gancho, para pendurar samambaias e jiboias. O prato encaixado segura a água da rega.",
    mat: "Polipropileno",
    cor: "Branco",
    h: 16,
    boca: 24,
    base: 16,
    cap: 3.5,
    furo: false,
    uso: "BOTH",
  },
  {
    n: "Cachepot de plástico grande com rodízios",
    c: "cachepots/plastico",
    p: 189,
    g: 1900,
    t: "Cachepot de 45 cm de boca com rodízios embutidos na base. Movimenta plantas grandes sem esforço.",
    mat: "Polipropileno",
    cor: "Grafite",
    h: 42,
    boca: 45,
    base: 32,
    cap: 40,
    furo: false,
    uso: "BOTH",
  },

  // ── Flores e plantas artificiais ──
  {
    n: "Trepadeira artificial de hera",
    c: "flores-e-plantas-artificiais",
    p: 59,
    g: 250,
    t: "Ramo de hera artificial com 1,80 m, de folhas em dois tons de verde. Usado para revestir treliças, estantes e arcos de festa.",
    mat: "Poliéster",
    cor: "Verde",
    h: 180,
    vaso: false,
    sub: "planta",
  },
  {
    n: "Kit 6 hastes de flores do campo artificiais",
    c: "flores-e-plantas-artificiais",
    p: 119,
    g: 400,
    t: "Seis hastes sortidas de flores do campo em tons claros, para montar o próprio arranjo em um vaso de boca estreita.",
    mat: "Tecido",
    cor: "Branco",
    h: 55,
    vaso: false,
    sub: "flor",
  },

  {
    n: "Folhagem artificial costela-de-adão",
    c: "flores-e-plantas-artificiais/plantas-e-flores",
    p: 89,
    g: 300,
    t: "Haste com sete folhas de costela-de-adão em material emborrachado, com nervuras em relevo. O verde tem brilho natural, sem aspecto de plástico.",
    mat: "Poliuretano",
    cor: "Verde",
    h: 75,
    vaso: false,
    sub: "planta",
  },
  {
    n: "Orquídea artificial de toque real",
    c: "flores-e-plantas-artificiais/plantas-e-flores",
    p: 149,
    g: 350,
    t: "Haste de Phalaenopsis em silicone, com pétalas que têm a textura e o peso das flores verdadeiras. Difícil de distinguir mesmo de perto.",
    mat: "Silicone",
    cor: "Branco",
    h: 95,
    vaso: false,
    sub: "flor",
  },
  {
    n: "Planta artificial em vaso grande",
    c: "flores-e-plantas-artificiais/plantas-e-flores",
    p: 890,
    g: 9500,
    t: "Ficus lyrata artificial de 1,60 m, com tronco de madeira natural e folhas emborrachadas. Vem plantado em vaso com acabamento de musgo.",
    mat: "Poliuretano e madeira",
    cor: "Verde",
    h: 160,
    vaso: true,
    sub: "planta",
  },
  {
    n: "Haste de eucalipto artificial",
    c: "flores-e-plantas-artificiais/plantas-e-flores",
    p: 49,
    g: 150,
    t: "Ramo de eucalipto com folhas arredondadas em verde-acinzentado e leve aspecto empoado, como o da planta fresca.",
    mat: "Poliéster",
    cor: "Verde",
    h: 70,
    vaso: false,
    sub: "planta",
  },

  {
    n: "Buquê de rosas artificiais",
    c: "flores-e-plantas-artificiais/buques",
    p: 129,
    g: 450,
    t: "Doze rosas de botão aberto em tecido aveludado, amarradas com fita. As pétalas têm degradê de cor, como nas rosas de jardim.",
    mat: "Tecido",
    cor: "Vermelho",
    h: 40,
    vaso: false,
    sub: "buquê",
    v: [
      ["Vermelho", { Cor: "Vermelho" }, 129],
      ["Branco", { Cor: "Branco" }, 129],
      ["Rosa", { Cor: "Rosa" }, 129],
    ],
  },
  {
    n: "Buquê de peônias artificiais",
    c: "flores-e-plantas-artificiais/buques",
    p: 189,
    g: 500,
    t: "Peônias de pétalas cheias em rosa-claro, com botões e folhagem. Um buquê volumoso para vasos de boca larga.",
    mat: "Tecido",
    cor: "Rosa",
    h: 45,
    vaso: false,
    sub: "buquê",
  },
  {
    n: "Buquê de lavanda artificial",
    c: "flores-e-plantas-artificiais/buques",
    p: 59,
    g: 200,
    t: "Maço de hastes de lavanda com espigas flocadas em lilás. Simples e perfumado só na aparência, combina com cozinhas e lavabos.",
    mat: "Polietileno",
    cor: "Lilás",
    h: 38,
    vaso: false,
    sub: "buquê",
  },
  {
    n: "Buquê de noiva de hortênsias artificiais",
    c: "flores-e-plantas-artificiais/buques",
    p: 290,
    g: 600,
    t: "Buquê redondo de hortênsias brancas e azuis, com cabo forrado de cetim. Usado em casamentos e ensaios, e guardado depois como lembrança.",
    mat: "Tecido",
    cor: "Azul",
    h: 30,
    vaso: false,
    sub: "buquê",
  },

  {
    n: "Vaso de vidro com rosas artificiais",
    c: "flores-e-plantas-artificiais/vasos-com-flores",
    p: 219,
    g: 1800,
    t: "Rosas artificiais em vaso de vidro com resina transparente, que imita água e mantém as hastes no lugar.",
    mat: "Tecido e vidro",
    cor: "Rosa",
    h: 32,
    l: 22,
    vaso: true,
    sub: "arranjo",
  },
  {
    n: "Cachepot com lavanda artificial",
    c: "flores-e-plantas-artificiais/vasos-com-flores",
    p: 89,
    g: 700,
    t: "Touceira de lavanda artificial plantada em cachepot de cerâmica cinza. Um ponto de cor para bancadas e criados-mudos.",
    mat: "Polietileno e cerâmica",
    cor: "Lilás",
    h: 28,
    l: 16,
    vaso: true,
    sub: "arranjo",
  },
  {
    n: "Vaso com orquídea artificial branca",
    c: "flores-e-plantas-artificiais/vasos-com-flores",
    p: 329,
    g: 2200,
    t: "Duas hastes de orquídea de toque real em cachepot de cerâmica, com folhas e raízes aparentes, como na planta viva.",
    mat: "Silicone e cerâmica",
    cor: "Branco",
    h: 60,
    l: 30,
    vaso: true,
    sub: "arranjo",
  },
  {
    n: "Vaso com suculenta artificial pendente",
    c: "flores-e-plantas-artificiais/vasos-com-flores",
    p: 480,
    g: 2600,
    t: "Suculentas pendentes do tipo rabo-de-burro em vaso alto de cerâmica. Os ramos caem pela lateral e pedem um aparador ou coluna.",
    mat: "Polietileno e cerâmica",
    cor: "Verde",
    h: 70,
    l: 28,
    vaso: true,
    sub: "planta",
  },

  // ── Decoração e aromas ──
  {
    n: "Kit decoração para aparador",
    c: "decoracao-e-aromas",
    p: 349,
    g: 3200,
    t: "Bandeja, vela aromática e vaso solitário escolhidos para ficarem juntos. Um conjunto pronto para aparador, lavabo ou mesa de centro.",
    mat: "Madeira, vidro e porcelana",
    cor: "Natural",
    h: 20,
    l: 35,
    uso: "INDOOR",
  },
  {
    n: "Livro caixa decorativo botânico",
    c: "decoracao-e-aromas",
    p: 89,
    g: 800,
    t: "Caixa em formato de livro com capa de ilustrações botânicas antigas. Guarda controles e pequenos objetos e compõe estantes.",
    mat: "MDF e papel",
    cor: "Verde",
    h: 5,
    l: 20,
    pr: 27,
    uso: "INDOOR",
  },

  {
    n: "Porta-velas de vidro e ferro 5 × 11 cm",
    c: "decoracao-e-aromas/objetos-de-decoracao",
    p: 29,
    g: 250,
    t: "Copo de vidro em armação de ferro preto, para velas do tipo rechaud. A chama fica protegida do vento em mesas externas.",
    mat: "Vidro e ferro",
    cor: "Preto",
    h: 11,
    l: 5,
    uso: "BOTH",
  },
  {
    n: "Porta-velas de vidro e ferro 9 × 10 cm",
    c: "decoracao-e-aromas/objetos-de-decoracao",
    p: 49,
    g: 400,
    t: "Modelo mais largo, que recebe velas de até 7 cm de diâmetro. A armação de ferro forma uma alça para transportar.",
    mat: "Vidro e ferro",
    cor: "Preto",
    h: 10,
    l: 9,
    uso: "BOTH",
  },
  {
    n: "Bandeja decorativa",
    c: "decoracao-e-aromas/objetos-de-decoracao",
    p: 189,
    g: 1400,
    t: "Bandeja de madeira com fundo espelhado e alças de metal dourado. Organiza velas, difusores e pequenos vasos em um só ponto.",
    mat: "Madeira e espelho",
    cor: "Dourado",
    h: 5,
    l: 38,
    pr: 24,
    uso: "INDOOR",
  },
  {
    n: "Terrário de vidro",
    c: "decoracao-e-aromas/objetos-de-decoracao",
    p: 290,
    g: 2400,
    t: "Estrutura geométrica de vidro e latão, com uma face aberta para o plantio. Acompanha guia de montagem com camadas de drenagem.",
    mat: "Vidro e latão",
    cor: "Dourado",
    h: 26,
    l: 20,
    pr: 20,
    uso: "INDOOR",
  },

  {
    n: "Difusor de varetas L'Envie",
    c: "decoracao-e-aromas/aromas-lenvie",
    p: 149,
    g: 600,
    t: "Frasco de 250 ml com oito varetas de fibra. Perfuma de forma contínua por cerca de dois meses.",
    marca: "L'Envie",
    mat: "Vidro",
    h: 25,
    uso: "INDOOR",
    sub: "difusor",
    v: [
      ["Figo e folhas verdes", { Fragrância: "Figo e folhas verdes" }, 149],
      ["Flor de laranjeira", { Fragrância: "Flor de laranjeira" }, 149],
      ["Bambu", { Fragrância: "Bambu" }, 149],
    ],
  },
  {
    n: "Home spray L'Envie",
    c: "decoracao-e-aromas/aromas-lenvie",
    p: 89,
    g: 350,
    t: "Spray de ambiente de 200 ml, para perfumar na hora cortinas, almofadas e roupas de cama.",
    marca: "L'Envie",
    mat: "Vidro",
    h: 18,
    uso: "INDOOR",
    sub: "spray",
    v: [
      ["Figo e folhas verdes", { Fragrância: "Figo e folhas verdes" }, 89],
      ["Lavanda", { Fragrância: "Lavanda" }, 89],
    ],
  },
  {
    n: "Vela aromática L'Envie",
    c: "decoracao-e-aromas/aromas-lenvie",
    p: 119,
    g: 500,
    t: "Vela de cera vegetal em copo de vidro, com 40 horas de queima. O pavio de algodão queima sem fumaça.",
    marca: "L'Envie",
    mat: "Cera vegetal e vidro",
    h: 9,
    uso: "INDOOR",
    sub: "vela",
    v: [
      ["Figo e folhas verdes", { Fragrância: "Figo e folhas verdes" }, 119],
      ["Flor de laranjeira", { Fragrância: "Flor de laranjeira" }, 119],
      ["Cedro", { Fragrância: "Cedro" }, 119],
    ],
  },
  {
    n: "Refil para difusor L'Envie",
    c: "decoracao-e-aromas/aromas-lenvie",
    p: 79,
    g: 300,
    t: "Refil de 250 ml para reabastecer o difusor de varetas. Troque as varetas a cada refil para manter a intensidade do aroma.",
    marca: "L'Envie",
    mat: "Embalagem plástica",
    h: 16,
    uso: "INDOOR",
    sub: "refil",
  },

  {
    n: "Escultura de cerâmica",
    c: "decoracao-e-aromas/linha-conceito",
    p: 490,
    g: 2800,
    t: "Forma orgânica modelada à mão em cerâmica branca fosca. Peça assinada da Linha Conceito, feita em pequena tiragem.",
    marca: "Linha Conceito",
    mat: "Cerâmica",
    cor: "Branco",
    h: 32,
    l: 18,
    uso: "INDOOR",
  },
  {
    n: "Vaso escultural",
    c: "decoracao-e-aromas/linha-conceito",
    p: 890,
    g: 5200,
    t: "Vaso de cerâmica com duas aberturas e corpo assimétrico, que funciona como escultura mesmo vazio.",
    marca: "Linha Conceito",
    mat: "Cerâmica",
    cor: "Areia",
    h: 42,
    boca: 10,
    base: 16,
    cap: 4,
    furo: false,
    uso: "INDOOR",
  },
  {
    n: "Centro de mesa de cerâmica orgânica",
    c: "decoracao-e-aromas/linha-conceito",
    p: 329,
    g: 2400,
    t: "Travessa de bordas irregulares e esmalte em tom de areia. Serve como fruteira ou como base para composições de suculentas.",
    marca: "Linha Conceito",
    mat: "Cerâmica",
    cor: "Areia",
    h: 8,
    l: 40,
    pr: 28,
    uso: "INDOOR",
  },
  {
    n: "Trio de vasos conceito",
    c: "decoracao-e-aromas/linha-conceito",
    p: 149,
    g: 1500,
    t: "Três vasos pequenos de formas diferentes e mesma paleta, pensados para ficar juntos. Cada um recebe um ramo ou uma flor.",
    marca: "Linha Conceito",
    mat: "Cerâmica",
    cor: "Branco",
    h: 14,
    boca: 4,
    base: 7,
    cap: 0.4,
    furo: false,
    uso: "INDOOR",
  },

  // ── Jardinagem ──
  {
    n: "Kit meu primeiro jardim",
    c: "jardinagem",
    p: 189,
    g: 2200,
    t: "Pá estreita, garfo, tesoura de poda, luvas e regador de bico fino. As cinco ferramentas que resolvem o cuidado com plantas de vaso.",
    marca: "Shopping Garden",
    sub: "Kits",
  },
  {
    n: "Avental de jardinagem",
    c: "jardinagem",
    p: 89,
    g: 350,
    t: "Avental de lona encerada com três bolsos frontais para tesoura, luvas e barbante. Protege a roupa da terra e da água.",
    marca: "Shopping Garden",
    sub: "Acessórios",
    mat: "Lona",
  },

  {
    n: "Tesoura de poda",
    c: "jardinagem/ferramentas-e-acessorios",
    p: 89,
    g: 280,
    t: "Lâminas de aço carbono com corte do tipo bypass, para ramos de até 20 mm. Tem trava de segurança e cabos emborrachados.",
    marca: "Verdejar",
    sub: "Tesouras",
    mat: "Aço carbono",
  },
  {
    n: "Pá de jardinagem",
    c: "jardinagem/ferramentas-e-acessorios",
    p: 39,
    g: 220,
    t: "Pá estreita de aço com cabo de madeira, para abrir covas e completar vasos com substrato. Tem escala em centímetros na lâmina.",
    marca: "Verdejar",
    sub: "Pás e garfos",
    mat: "Aço e madeira",
  },
  {
    n: "Garfo de jardinagem",
    c: "jardinagem/ferramentas-e-acessorios",
    p: 39,
    g: 210,
    t: "Garfo de três dentes para afofar a terra e soltar raízes na hora do transplante, sem ferir a planta.",
    marca: "Verdejar",
    sub: "Pás e garfos",
    mat: "Aço e madeira",
  },
  {
    n: "Luvas de jardinagem",
    c: "jardinagem/ferramentas-e-acessorios",
    p: 29,
    g: 90,
    t: "Luvas de malha com palma revestida de nitrilo, que protegem de espinhos e mantêm o tato para trabalhos delicados.",
    marca: "Shopping Garden",
    sub: "Luvas",
    mat: "Poliéster e nitrilo",
    v: [
      ["Pequena", { Tamanho: "P" }, 29],
      ["Média", { Tamanho: "M" }, 29],
      ["Grande", { Tamanho: "G" }, 29],
    ],
  },

  {
    n: "Adubo NPK 10-10-10 1 kg",
    c: "jardinagem/adubos-e-fertilizantes",
    p: 29,
    g: 1050,
    t: "Adubo mineral granulado com nitrogênio, fósforo e potássio em partes iguais. Indicado para manutenção de folhagens, gramados e arbustos.",
    marca: "Folha Nova",
    sub: "Adubo mineral",
  },
  {
    n: "Adubo orgânico 2 kg",
    c: "jardinagem/adubos-e-fertilizantes",
    p: 35,
    g: 2100,
    t: "Composto de esterco curtido e farinha de ossos, que melhora a estrutura da terra e libera nutrientes aos poucos.",
    marca: "Terra Viva",
    sub: "Adubo orgânico",
  },
  {
    n: "Adubo para orquídeas 400 g",
    c: "jardinagem/adubos-e-fertilizantes",
    p: 39,
    g: 450,
    t: "Fórmula para floração, com mais fósforo. Dissolve na água da rega e deve ser aplicado a cada quinze dias.",
    marca: "Folha Nova",
    sub: "Adubo mineral",
  },
  {
    n: "Bokashi 1 kg",
    c: "jardinagem/adubos-e-fertilizantes",
    p: 45,
    g: 1050,
    t: "Adubo orgânico fermentado, rico em microrganismos que ativam a vida do solo. Muito usado em hortas e em vasos de orquídeas.",
    marca: "Terra Viva",
    sub: "Adubo orgânico",
  },

  {
    n: "Substrato para orquídeas 2 kg",
    c: "jardinagem/substratos",
    p: 32,
    g: 2050,
    t: "Mistura de casca de pinus, fibra de coco e carvão vegetal, que mantém as raízes arejadas e drena rápido.",
    marca: "Terra Viva",
    sub: "Substrato",
  },
  {
    n: "Substrato para suculentas 2 kg",
    c: "jardinagem/substratos",
    p: 28,
    g: 2050,
    t: "Mistura arenosa com perlita, que seca depressa e evita o apodrecimento de cactos e suculentas.",
    marca: "Terra Viva",
    sub: "Substrato",
  },
  {
    n: "Terra vegetal 5 kg",
    c: "jardinagem/substratos",
    p: 19,
    g: 5100,
    t: "Terra peneirada e enriquecida com matéria orgânica, para completar vasos e canteiros. Base para a maioria das misturas.",
    marca: "Terra Viva",
    sub: "Terra",
  },
  {
    n: "Substrato para folhagens 5 kg",
    c: "jardinagem/substratos",
    p: 29,
    g: 5100,
    t: "Mistura leve com turfa e casca compostada, que retém umidade na medida para plantas tropicais de interior.",
    marca: "Folha Nova",
    sub: "Substrato",
  },

  {
    n: "Argila expandida 2 L",
    c: "jardinagem/produtos-para-plantio",
    p: 22,
    g: 900,
    t: "Bolinhas de argila queimada usadas no fundo do vaso, como camada de drenagem, e na superfície, como acabamento.",
    marca: "Terra Viva",
    sub: "Drenagem",
  },
  {
    n: "Manta de drenagem",
    c: "jardinagem/produtos-para-plantio",
    p: 12,
    g: 100,
    t: "Manta de poliéster de 1 m², que separa a terra da camada de drenagem e impede o entupimento dos furos do vaso.",
    marca: "Terra Viva",
    sub: "Drenagem",
  },
  {
    n: "Casca de pinus 5 L",
    c: "jardinagem/produtos-para-plantio",
    p: 24,
    g: 1200,
    t: "Casca de pinus em pedaços médios, para cobrir a terra de vasos e canteiros. Conserva a umidade e reduz o mato.",
    marca: "Terra Viva",
    sub: "Cobertura",
  },
  {
    n: "Pedrisco branco 2 kg",
    c: "jardinagem/produtos-para-plantio",
    p: 18,
    g: 2050,
    t: "Pedras brancas de dolomita para o acabamento de vasos de suculentas, cactos e terrários.",
    marca: "Terra Viva",
    sub: "Cobertura",
  },

  {
    n: "Óleo de neem 100 ml",
    c: "jardinagem/defensivos",
    p: 39,
    g: 130,
    t: "Extrato vegetal concentrado para o controle de cochonilhas, pulgões e ácaros. Diluído em água, rende até 20 litros de calda.",
    marca: "Folha Nova",
    sub: "Inseticida natural",
  },
  {
    n: "Sabão potássico 500 ml",
    c: "jardinagem/defensivos",
    p: 29,
    g: 550,
    t: "Pronto para uso, com borrifador. Age por contato sobre insetos de corpo mole e pode ser usado em hortas.",
    marca: "Folha Nova",
    sub: "Inseticida natural",
  },
  {
    n: "Fungicida de calda bordalesa 250 ml",
    c: "jardinagem/defensivos",
    p: 35,
    g: 300,
    t: "Calda à base de cobre e cal, usada há mais de um século contra manchas nas folhas e fungos em roseiras e frutíferas.",
    marca: "Folha Nova",
    sub: "Fungicida",
  },
  {
    n: "Armadilha adesiva amarela",
    c: "jardinagem/defensivos",
    p: 15,
    g: 60,
    t: "Dez cartões adesivos amarelos que atraem e prendem mosquinhas de vaso e moscas-brancas, sem uso de produtos químicos.",
    marca: "Folha Nova",
    sub: "Armadilhas",
  },

  {
    n: "Regador 5 L",
    c: "jardinagem/irrigacao",
    p: 69,
    g: 450,
    t: "Regador de plástico resistente com crivo removível, que solta a água em chuveiro fino para não deslocar a terra.",
    marca: "Verdejar",
    sub: "Regadores",
  },
  {
    n: "Pulverizador 1 L",
    c: "jardinagem/irrigacao",
    p: 35,
    g: 180,
    t: "Borrifador com bico regulável, do jato à névoa. Para umedecer folhas de samambaias e aplicar caldas.",
    marca: "Verdejar",
    sub: "Pulverizadores",
  },
  {
    n: "Mangueira 15 m",
    c: "jardinagem/irrigacao",
    p: 189,
    g: 2600,
    t: "Mangueira trançada de três camadas, flexível e resistente a dobras. Acompanha esguicho e engates rápidos.",
    marca: "Verdejar",
    sub: "Mangueiras",
  },
  {
    n: "Regador de bico fino 1 L",
    c: "jardinagem/irrigacao",
    p: 49,
    g: 220,
    t: "Regador de metal com bico longo e fino, que leva a água direto à terra em vasos pequenos e apertados.",
    marca: "Shopping Garden",
    sub: "Regadores",
  },
];
